name: Continuous Integration (CI)

on:
  push:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: PMD
        uses: pmd/pmd-github-action@v1.4.1
        with:
          version: '7.0.0-rc4'
          sourcePath: 'src/main/java'
          rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'
      - name: Set gradlew as executable
        run: chmod +x ./gradlew
      - name: Run tests
        run: ./gradlew test